project_id = "fqtfmhlevdhaitkyoyzr"

[functions.create-user]
verify_jwt = true

[functions.update-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.auto-close-sessions]
verify_jwt = false
